spring:
  application:
    name: payment-demo

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true


  # 클라이언트 API 계약 설정 파일 import
  config:
    import: optional:classpath:client-api-config.yml

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  security:
    user:
      name: demo
      password: demo123

server:
  port: 8080
  servlet:
    context-path: /

# PortOne Configuration
portone:
  api:
    base-url: https://api.portone.io
    secret: ${PORTONE_API_SECRET:0OqOAuGcMrWpW6NQnyP30kLcuLlCpOUDlqMr9vzoAMNGkIeiRL1XT0AmqHam8Zc24cFepwCFq4NQJtci}
  store:
    id: ${PORTONE_STORE_ID:store-148bcbf7-e1c9-4211-ab2c-4af225987ebb}
  channel:
    kg-inicis: ${PORTONE_CHANNEL_KG:channel-key-877b20df-6f93-412b-bb24-a45461a7261e}
    toss: ${PORTONE_CHANNEL_TOSS:channel-key-b1b6ba35-6266-41ac-9074-a9675b4caa54}
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:commercehub-secret-key-for-demo-please-change-this-in-production-environment}
  token-validity-in-seconds: ${JWT_VALIDITY:86400}  # 24 hours


# UI Branding Configuration
app:
  ui:
    branding:
      app-name: CommerceHub
      tagline: 통합 커머스 플랫폼
      logo-text: 🏪 CommerceHub

logging:
  level:
    com.bootcamp.paymentdemo: DEBUG
    org.springframework.security: INFO
